sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=alllomancer/helloworld
    - REGISTRY_USER=alllomancer
    - REGISTRY_EMAIL=dan.yelovitch@gmail.com
before_script:
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

after_script:
  - docker images

before_deploy:
  - docker login --username="$REGISTRY_USER" --email="REGISTRY_EMAIL"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master